apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-sql
data:
  create-multiple-dbs.sql: |
    -- Pastikan user bisa replication
    ALTER ROLE user WITH REPLICATION;

    -- Database tambahan
    CREATE DATABASE data_staging;
    CREATE DATABASE backup;