apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-sql
data:
  create-multiple-dbs.sql: |
    ALTER ROLE user WITH REPLICATION;

    CREATE DATABASE data_staging;
    CREATE DATABASE backup;
