services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: Staging/postgres
    restart: unless-stopped
    hostname: ${POSTGRES_CONTAINER_NAME}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../sql:/sql
      - ../data:/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - Batching-Processing
      - Streaming-Processing

  pgadmin:
    image: dpage/pgadmin4:9.1.0
    container_name: ${POSTGRES_CONTAINER_NAME_UI}
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
    ports:
      - ${POSTGRES_PORT_UI}:80
    depends_on:
      - postgres
    networks:
      - Batching-Processing
      - Streaming-Processing

networks:
  Batching-Processing:
    external: true
  Streaming-Processing:
    external: true