services:
  zookeeper:
    container_name: ${ZOOKEEPER_CONTAINER_NAME}
    image: confluentinc/cp-zookeeper:7.9.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    restart: unless-stopped

  kafka:
    container_name: ${KAFKA_CONTAINER_NAME}
    image: Streaming/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "${KAFKA_PORT}:9092"
    depends_on:
      - zookeeper

  schema-registry:
    container_name: ${KAFKA_SCHEMA_REGISTRY}
    image: confluentinc/cp-schema-registry:7.9.4
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: ${KAFKA_SCHEMA_REGISTRY_HOST_NAME}
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_DEBUG: true
    ports:
      - "${KAFKA_SCHEMA_REGISTRY_PORT}:8081"
    depends_on:
      - kafka

  ksqldb-server:
    container_name: ${KSQL_CONTAINER_NAME}
    image: confluentinc/ksqldb-server:0.29.0
    environment:
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    ports:
      - "${KSQL_PORT}:8088"
    depends_on:
      - kafka
      - schema-registry

  debezium:
    container_name: ${DEBEZIUM_CONTAINER_NAME}
    image: Streaming/debezium
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_GROUP_ID: ${DEBEZIUM_ID}
      CONNECT_CONFIG_STORAGE_TOPIC: connect_configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect_offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect_statuses
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: false
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: false
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE: false
      CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE: false
      CONNECT_PLUGIN_PATH: /opt/connectors,/usr/share/java
      CONNECT_REST_PORT: ${CONNECT_REST_PORT}
      CONNECT_REST_ADVERTISED_HOST_NAME: ${CONNECT_REST_ADVERTISED_HOST_NAME}
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
    ports:
      - "${DEBEZIUM_PORT}:8083"
    depends_on:
      - kafka
      - schema-registry

  kafka-ui:
    container_name: ${KAFKA_UI}
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    ports:
      - "${KAFKA_UI_PORT}:8080"
    depends_on:
      - kafka
      - schema-registry
      - ksqldb-server

  debezium-ui:
    container_name: ${DEBEZIUM_UI}
    image: debezium/debezium-ui:latest
    volumes:
      - ./file/debezium-ui.properties:/debezium-ui/config/application.properties
    ports:
      - "${DEBEZIUM_UI_PORT}:8080"
    depends_on:
      - debezium

networks:
  default:
    name: Streaming-Processing
    external: true