services:
  spark-master:
    container_name: ${SPARK_MASTER_CONTAINER_NAME}
    hostname: ${SPARK_MASTER_HOST_NAME}
    image: Batching/spark
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=${SPARK_MASTER_HOST_NAME}
      - SPARK_MASTER_PORT=${SPARK_MASTER_PORT}
      - SPARK_MASTER_UI_PORT=8080
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master \
      --host ${SPARK_MASTER_HOST_NAME} --port ${SPARK_MASTER_PORT} --webui-port 8080"
    ports:
      - "${SPARK_MASTER_UI}:8080"
      - "${SPARK_MASTER_PORT}:7077"
    volumes:
      - ../spark-scripts:/spark-scripts
      - ../scripts:/scripts
      - ../data:/data
      - ../logs:/tmp

  spark-worker:
    container_name: ${SPARK_WORKER_CONTAINER_NAME}
    image: Batching/spark
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://${SPARK_MASTER_HOST_NAME}:${SPARK_MASTER_PORT}
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker \
      spark://${SPARK_MASTER_HOST_NAME}:${SPARK_MASTER_PORT}"
    volumes:
      - ../spark-scripts:/spark-scripts
      - ../scripts:/scripts
      - ../data:/data
      - ../logs:/tmp

networks:
  default:
    name: Batching-Processing
    external: true