services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: staging_postgres
    restart: always
    hostname: ${POSTGRES_CONTAINER_NAME}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - Batching-Processing
      - Streaming-Processing

  pgadmin:
    image: dpage/pgadmin4:9.1.0
    container_name: ${POSTGRES_CONTAINER_NAME_UI}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin   
    ports:
      - ${POSTGRES_PORT_UI}:80
    depends_on:
      - postgres
    networks:
      - Batching-Processing
      - Streaming-Processing
      
volumes:
  postgres_data:
    name: postgres_database
  pgadmin_data:
    name: postgres_ui_pgadmin

networks:
  Batching-Processing:
    external: true
  Streaming-Processing:
    external: true