apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  labels:
    app: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
        # ======================
        # Spark Master (DRIVER)
        # ======================
        - name: spark-master
          image: ajied21/spark:latest
          imagePullPolicy: IfNotPresent

          command:
            - "/opt/spark/bin/spark-class"
            - "org.apache.spark.deploy.master.Master"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "7077"
            - "--webui-port"
            - "8080"

          ports:
            - containerPort: 7077
            - containerPort: 8080

          volumeMounts:
            - name: spark-logs
              mountPath: /tmp
            - name: spark-data
              mountPath: /home/spark-master-data   # ✅ OUTPUT PYTHON
            - name: spark-scripts
              mountPath: /opt/app           # ✅ PYTHON SCRIPT

        # ======================
        # Spark Worker
        # ======================
        - name: spark-worker
          image: ajied21/spark:latest
          imagePullPolicy: IfNotPresent

          command:
            - "/opt/spark/bin/spark-class"
            - "org.apache.spark.deploy.worker.Worker"
            - "spark://localhost:7077"

          ports:
            - containerPort: 8081
            - containerPort: 9102

          volumeMounts:
            - name: spark-logs
              mountPath: /tmp
            - name: spark-data
              mountPath: /home/spark-master-data

      volumes:
        - name: spark-logs
          persistentVolumeClaim:
            claimName: spark-logs-pvc

        - name: spark-data
          persistentVolumeClaim:
            claimName: spark-data-pvc

        - name: spark-scripts
          emptyDir: {}   # script dicopy via kubectl cp