apiVersion: v1
kind: Service
metadata:
  name: spark
spec:
  selector:
    app: spark
  ports:
    - name: master
      port: 7077
      targetPort: 7077
    - name: master-ui
      port: 8080
      targetPort: 8080
    - name: worker-ui
      port: 8081
      targetPort: 8081
    - name: worker-metrics
      port: 9102
      targetPort: 9102
  type: ClusterIP