apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium
  labels:
    app: debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
        - name: debezium
          image: ajied21/debezium:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8083

          env:
            # Kafka Bootstrap
            - name: BOOTSTRAP_SERVERS
              value: "kafka:9092"

            # Kafka Connect Cluster
            - name: GROUP_ID
              value: "debezium-connect-cluster"

            # Internal Topics
            - name: CONFIG_STORAGE_TOPIC
              value: "_debezium_config"
            - name: OFFSET_STORAGE_TOPIC
              value: "_debezium_offset"
            - name: STATUS_STORAGE_TOPIC
              value: "_debezium_status"

            # single-broker Kafka
            - name: CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"

            # Converters
            - name: KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"

            - name: KEY_CONVERTER_SCHEMAS_ENABLE
              value: "false"
            - name: VALUE_CONVERTER_SCHEMAS_ENABLE
              value: "false"

            - name: INTERNAL_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: INTERNAL_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"

            # REST API
            - name: REST_ADVERTISED_HOST_NAME
              value: "debezium"
            - name: REST_PORT
              value: "8083"

            # Plugin Path
            - name: PLUGIN_PATH
              value: "/kafka/connect"
