apiVersion: v1
kind: ConfigMap
metadata:
  name: debezium-connectors
data:
  data_lake-cdc-connector.json: |
    {
      "name": "data_lake-cdc-connector",
      "config": {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",

        "database.hostname": "postgres",
        "database.port": "5432",
        "database.user": "user",
        "database.password": "admin123",
        "database.dbname": "data_lake",

        "topic.prefix": "data_lake",
        "plugin.name": "pgoutput",

        "table.include.list": "public.bronze_customer_raw,public.bronze_orders_raw,public.bronze_payments_raw,public.bronze_shipping_raw,public.bronze_product_raw",

        "slot.name": "data_lake_slot",
        "publication.autocreate.mode": "filtered",

        "snapshot.mode": "initial",
        "tombstones.on.delete": "false"
      }
    }

  data_staging-cdc-connector.json: |
    {
      "name": "data_staging-cdc-connector",
      "config": {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",

        "database.hostname": "postgres",
        "database.port": "5432",
        "database.user": "user",
        "database.password": "admin123",
        "database.dbname": "data_staging",

        "topic.prefix": "data_staging",
        "plugin.name": "pgoutput",

        "table.include.list": "public.bronze_customer_raw,public.bronze_orders_raw,public.bronze_payments_raw,public.bronze_shipping_raw,public.bronze_product_raw",

        "slot.name": "data_staging_slot",
        "publication.autocreate.mode": "filtered",

        "snapshot.mode": "initial",
        "tombstones.on.delete": "false"
      }
    }