apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-conf
data:
  flink-conf.yaml: |
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 2
    parallelism.default: 1
    blob.server.port: 6124
    rest.bind-address: 0.0.0.0
    rest.port: 8081